# Persistent Volume claims for permanent storage
# The annotation will storage-class will auto provision storage
# on certain cloud providers (GCE, AWS)
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openam-pvc-a
  namespace: forgerock
  # annotations:
  #   volume.alpha.kubernetes.io/storage-class: foo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opendj-storage
  namespace: forgerock
  # annotations:
  #   volume.alpha.kubernetes.io/storage-class: foo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-storage
  namespace: forgerock
  # annotations:
  #   volume.alpha.kubernetes.io/storage-class: foo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
